send:
  fields:
    phone_number:
      required: true
      example: "+33612345678"
      selector:
        text:
    message:
      required: true
      selector:
        text:
          multiline: true
delete:
  fields:
    message_id:
      required: true
      example: 40145
      selector:
        number:
          min: 0
          mode: box
delete_all: {}
add_contact:
  fields:
    name:
      required: true
      selector:
        text:
    phone_number:
      required: true
      selector:
        text:
delete_contact:
  fields:
    contact_id:
      required: true
      selector:
        number:
          min: 0
          mode: box

enable_pin:
  fields:
    current_pin:
      required: true
      selector:
        text:
          type: password

disable_pin:
  fields:
    current_pin:
      required: true
      selector:
        text:
          type: password

change_pin:
  fields:
    current_pin:
      required: true
      selector:
        text:
          type: password
    new_pin:
      required: true
      selector:
        text:
          type: password

get_pin_status: {}

verify_pin:
  fields:
    current_pin:
      required: true
      selector:
        text:
          type: password
